// Generated by nuxi
/// <reference types="@nuxtjs/apollo" />
/// <reference types="@formkit/nuxt" />
/// <reference types="@sidebase/nuxt-auth" />
/// <reference types="nuxt-highcharts" />
/// <reference types="nuxt-monaco-editor" />
/// <reference types="@nuxt/content" />
/// <reference types="@huntersofbook/naive-ui-nuxt" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference path="types/auth.d.ts" />
/// <reference path="types/content.d.ts" />
/// <reference path="types/naive-ui.d.ts" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
